# Generated by Django 5.0.6 on 2025-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'add_demo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('I', 'Modalidad Individual'), ('G', 'Modalidad Grupal'), ('S', 'Superadmin')], default='I', help_text='Indica si el usuario pertenece a modalidad individual (I), grupal (G) o es superadmin (S)', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(default='M', help_text='Letra que identifica el plan específico (M: mensual, NT: no tiene plan, etc.)', max_length=2),
        ),
    ]
