# Generated by Django 5.0.6 on 2025-05-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha sido verificado'),
        ),
    ]
