# Generated by Django 5.0.6 on 2025-06-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrador',
            field=models.ForeignKey(blank=True, help_text='Administrador al que está asociado este usuario (para modalidad grupal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('I', 'Modalidad Individual'), ('G', 'Modalidad Grupal')], default='I', help_text='Indica si el usuario pertenece a modalidad individual (I) o grupal (G)', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(default='M', help_text='Letra que identifica el plan específico (M: mensual, etc.)', max_length=1),
        ),
    ]
