# Generated by Django 5.0.6 on 2025-06-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_administrador_user_modalidad_user_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
    ]
