# Generated by Django 5.0.6 on 2025-06-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_verify'),
        ('users', 'add_superadmin_role'),
    ]

    operations = [
    ]
