# Generated by Django 5.0.6 on 2025-03-29 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0002_remove_audit_company_remove_audit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceCuentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_balance', models.CharField(choices=[('ANUAL', 'Anual'), ('SEMESTRAL', 'Semestral')], max_length=10, verbose_name='Tipo de Balance')),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('seccion', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio')], max_length=10, verbose_name='Sección')),
                ('nombre_cuenta', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='audits.audit', verbose_name='Auditoría')),
            ],
            options={
                'verbose_name': 'Balance de Cuentas',
                'verbose_name_plural': 'Balances de Cuentas',
                'ordering': ['audit', 'tipo_balance', 'fecha_corte', 'seccion', 'nombre_cuenta'],
            },
        ),
    ]
