# Generated by Django 5.0.6 on 2025-04-10 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('audits', '0002_remove_audit_company_remove_audit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuxiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta', models.CharField(max_length=100, verbose_name='Cuenta')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo')),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_auxiliares', to='audits.audit', verbose_name='Auditoría')),
            ],
            options={
                'verbose_name': 'Registro Auxiliar',
                'verbose_name_plural': 'Registros Auxiliares',
                'ordering': ['audit', 'cuenta'],
            },
        ),
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta', models.CharField(max_length=100, verbose_name='Cuenta')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo Inicial')),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_iniciales', to='audits.audit', verbose_name='Auditoría')),
            ],
            options={
                'verbose_name': 'Saldo Inicial',
                'verbose_name_plural': 'Saldos Iniciales',
                'ordering': ['audit', 'cuenta'],
            },
        ),
    ]
