# Generated by Django 5.0.6 on 2025-04-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_registroauxiliar_saldoinicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroauxiliar',
            name='fecha_corte',
        ),
    ]
