# Generated by Django 5.0.6 on 2025-07-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_remove_registroauxiliar_fecha_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecuentas',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cuenta'),
        ),
    ]
