# Generated by Django 5.0.6 on 2025-08-05 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_balancecuentas_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecuentas',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debe'),
        ),
        migrations.AddField(
            model_name='balancecuentas',
            name='haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haber'),
        ),
    ]
