# Generated by Django 5.0.6 on 2025-08-06 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_balancecuentas_debe_balancecuentas_haber'),
        ('audits', '0002_remove_audit_company_remove_audit_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancecuentas',
            name='debe',
        ),
        migrations.RemoveField(
            model_name='balancecuentas',
            name='haber',
        ),
        migrations.CreateModel(
            name='AjustesReclasificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haber')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_reclasificaciones', to='audits.audit', verbose_name='Auditoría')),
            ],
            options={
                'verbose_name': 'Ajuste / Reclasificación',
                'verbose_name_plural': 'Ajustes / Reclasificaciones',
                'ordering': ['audit', 'nombre_cuenta'],
            },
        ),
    ]
