# Generated by Django 5.0.6 on 2025-02-25 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='description',
        ),
        migrations.AddField(
            model_name='audit',
            name='fechaEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='audit',
            name='fechaInit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='audit',
            name='identidad',
            field=models.CharField(default='Sin identidad', max_length=255),
        ),
        migrations.AddField(
            model_name='audit',
            name='tipoAuditoria',
            field=models.CharField(default='F', max_length=255),
        ),
    ]
