# Generated by Django 5.0.6 on 2025-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_remove_audit_company_remove_audit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='moneda',
            field=models.CharField(default='GTQ', max_length=10),
        ),
    ]
