# Generated by Django 5.0.6 on 2024-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittimesummary',
            name='appointment_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='appointment_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workingpapersstatus',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AppointmentNumber',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
