# Generated by Django 5.0.6 on 2024-11-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('tools', '0003_remove_activity_month_remove_activity_total_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_audit', to='audits.audit'),
        ),
    ]
