# Generated by Django 5.0.6 on 2024-11-16 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_activity_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='days',
            field=models.IntegerField(default=31, validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='months',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
